version: 2

updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Kolkata
    labels:
      - dependencies
    assignees:
      - Subhransu-De

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Kolkata
    labels:
      - dependencies
    assignees:
      - Subhransu-De
