services:
  qbittorrent-nox:
    image: qbittorrentofficial/qbittorrent-nox:${NOX_VERSION:-latest}
    pull_policy: always
    environment:
      - QBT_EULA=accept
      - QBT_WEBUI_PORT=8080
    ports:
      - "8080:8080/tcp"
      - "6881:6881/tcp"
      - "6881:6881/udp"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    tmpfs:
      - /tmp
    read_only: true
    stop_grace_period: 1800s
    restart: unless-stopped
